-- -------------------------
-- MOVIES
-- -------------------------
CREATE TABLE movies (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title        VARCHAR(120) NOT NULL,
                        release_year INT          NOT NULL,
                        genre        VARCHAR(30)  NOT NULL,
                        active       BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX uk_movie_title ON movies(title);

-- -------------------------
-- ACTORS
-- -------------------------
CREATE TABLE actors (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        stage_name  VARCHAR(80)  NOT NULL,
                        full_name   VARCHAR(120) NOT NULL,
                        nationality VARCHAR(60),
                        active      BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX uk_actor_stage_name ON actors(stage_name);

-- -------------------------
-- MOVIE_CAST (tabla intermedia N:M con atributos)
-- Un actor NO puede repetir la misma película (PK compuesta)
-- -------------------------
CREATE TABLE movie_cast (
                            movie_id        BIGINT        NOT NULL,
                            actor_id        BIGINT        NOT NULL,
                            character_name  VARCHAR(80)   NOT NULL,
                            screen_minutes  INT           NOT NULL,
                            salary_override DECIMAL(12,2),
                            active          BOOLEAN       NOT NULL,

                            CONSTRAINT pk_movie_cast PRIMARY KEY (movie_id, actor_id),
                            CONSTRAINT fk_mc_movie   FOREIGN KEY (movie_id) REFERENCES movies(id),
                            CONSTRAINT fk_mc_actor   FOREIGN KEY (actor_id) REFERENCES actors(id)
);

CREATE INDEX idx_movie_cast_movie ON movie_cast(movie_id);
CREATE INDEX idx_movie_cast_actor ON movie_cast(actor_id);